version: '2.1'
services:
  mongodb:
    image: mongo:3.6.9
    mem_limit: 350m
    ports:
      - "27017:27017"
    command: mongod --smallfiles

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_USER=user
      - POSTGRES_DB=review-db
    healthcheck:
      test: [ "CMD", "pg_isready", "-U","user","--dbname", "${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 10
  product:
    build: microservices/product-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongodb

  recommendation:
    build: microservices/recommendation-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongodb

  review:
    build: microservices/review-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      postgres:
        condition: service_healthy

  product-composite:
    build: microservices/product-composite-service
    mem_limit: 350m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker