server.port: 7001
server.error.include-message: always
spring.application.name: product

logging:
  level:
    root: INFO
    se.magnus: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG


spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-db
      auto-index-creation: true

spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings.input:
    destination: products
    group: productsGroup

spring.cloud.stream.bindings.input.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0

spring.cloud.stream.rabbit.bindings.input.consumer:
  autoBindDlq: true
  republishToDlq: true

spring.cloud.stream.kafka.bindings.input.consumer:
  enableDlq: true

spring.cloud.stream.kafka.binder:
  brokers: 127.0.0.1
  defaultBrokerPort: 9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

ribbon.ServerListRefreshInterval: 5000
ribbon.NFLoadBalancerPingInterval: 5



spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest
---

spring.profiles: docker
server.port: 8080
eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/

spring.rabbitmq.host: rabbitmq

spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: product-db
      auto-index-creation: true
